#!/bin/sh
#
#

# PROVIDE: komga
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Configuration settings for komga in /etc/rc.conf:
#
# komga_enable (bool):
#   Set to "NO" by default.
#   Set it to "YES" to enable komga.
#
# komga_home (str):
#   komga data dir
#   Set to "/var/komga" by default.
#
# komga_port (int):
#   Set to "8080" by default.
#
# komga_user (str):
#   set to "www" by default
#
# komga_group (str):
#   set to "www" by default
#


. /etc/rc.subr

name=komga
rcvar=${name}_enable
procname="/usr/local/openjdk11/bin/java"

load_rc_config "${name}"

: ${komga_enable:="NO"}
: ${komga_user:="www"}
: ${komga_group:="www"}
: ${komga_home:="/media/data"}
: ${komga_port:="8080"}

start_precmd="export LC_CTYPE='en_US.UTF-8'"
komga_chdir="/usr/local/share/komga"
command="/usr/sbin/daemon"
command_args="-f ${procname} \
        -Dkomga.config-dir=${komga_home} \
        -Dserver.port=${komga_port} \
        -jar ${komga_chdir}/komga.jar"

run_rc_command "$1"
